/**
 * Constantes para la app.
 */
export const APP_UPDATE = 'APP_UPDATE';
export const APP_MENU_DISPLAY = 'APP_MENU_DISPLAY';

/**
 * Constantes para acciones de rol.
 */
export const FETCH_ROLES_REQUEST = 'FETCH_ROLES_REQUEST';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_ERROR = 'FETCH_ROLES_ERROR';
export const FETCH_ROLES_BY_ID_REQUEST = 'FETCH_ROLES_BY_ID_REQUEST';
export const FETCH_ROLES_BY_ID_SUCCESS = 'FETCH_ROLES_BY_ID_SUCCESS';
export const FETCH_ROLES_BY_ID_ERROR = 'FETCH_ROLES_BY_ID_ERROR';
export const INSERT_ROLES_REQUEST = 'INSERT_ROLES_REQUEST';
export const INSERT_ROLES_SUCCESS = 'INSERT_ROLES_SUCCESS';
export const INSERT_ROLES_ERROR = 'INSERT_ROLES_ERROR';
export const UPDATE_ROLES_REQUEST = 'UPDATE_ROLES_REQUEST';
export const UPDATE_ROLES_SUCCESS = 'UPDATE_ROLES_SUCCESS';
export const UPDATE_ROLES_ERROR = 'UPDATE_ROLES_ERROR';
export const DELETE_ROLES_REQUEST = 'DELETE_ROLES_REQUEST';
export const DELETE_ROLES_SUCCESS = 'DELETE_ROLES_SUCCESS';
export const DELETE_ROLES_ERROR = 'DELETE_ROLES_ERROR';
export const ROLES_SET_CURRENT = 'ROLES_SET_CURRENT';
export const ROLES_SET_META = 'ROLES_SET_META';
export const ROLES_ADD_PERMISO_REQUEST = 'ROLES_ADD_PERMISO_REQUEST';
export const ROLES_ADD_PERMISO_SUCCESS = 'ROLES_ADD_PERMISO_SUCCESS';
export const ROLES_ADD_PERMISO_ERROR = 'ROLES_ADD_PERMISO_ERROR';
export const ROLES_DELETE_PERMISO_REQUEST = 'ROLES_DELETE_PERMISO_REQUEST';
export const ROLES_DELETE_PERMISO_SUCCESS = 'ROLES_DELETE_PERMISO_SUCCESS';
export const ROLES_DELETE_PERMISO_ERROR = 'ROLES_DELETE_PERMISO_ERROR';

/**
 * Constantes para acciones de marcas.
 */
export const FETCH_MARCAS_REQUEST = 'FETCH_MARCAS_REQUEST';
export const FETCH_MARCAS_SUCCESS = 'FETCH_MARCAS_SUCCESS';
export const FETCH_MARCAS_ERROR = 'FETCH_MARCAS_ERROR';
export const FETCH_MARCAS_BY_ID_REQUEST = 'FETCH_MARCAS_BY_ID_REQUEST';
export const FETCH_MARCAS_BY_ID_SUCCESS = 'FETCH_MARCAS_BY_ID_SUCCESS';
export const FETCH_MARCAS_BY_ID_ERROR = 'FETCH_MARCAS_BY_ID_ERROR';
export const INSERT_MARCAS_REQUEST = 'INSERT_MARCAS_REQUEST';
export const INSERT_MARCAS_SUCCESS = 'INSERT_MARCAS_SUCCESS';
export const INSERT_MARCAS_ERROR = 'INSERT_MARCAS_ERROR';
export const UPDATE_MARCAS_REQUEST = 'UPDATE_MARCAS_REQUEST';
export const UPDATE_MARCAS_SUCCESS = 'UPDATE_MARCAS_SUCCESS';
export const UPDATE_MARCAS_ERROR = 'UPDATE_MARCAS_ERROR';
export const DELETE_MARCAS_REQUEST = 'DELETE_MARCAS_REQUEST';
export const DELETE_MARCAS_SUCCESS = 'DELETE_MARCAS_SUCCESS';
export const DELETE_MARCAS_ERROR = 'DELETE_MARCAS_ERROR';
export const MARCAS_SET_CURRENT = 'MARCAS_SET_CURRENT';

/**
 * Constantes para acciones de usuarios.
 */
export const FETCH_USUARIOS_REQUEST = 'FETCH_USUARIOS_REQUEST';
export const FETCH_USUARIOS_SUCCESS = 'FETCH_USUARIOS_SUCCESS';
export const FETCH_USUARIOS_ERROR = 'FETCH_USUARIOS_ERROR';
export const FETCH_USUARIOS_BY_ID_REQUEST = 'FETCH_USUARIOS_BY_ID_REQUEST';
export const FETCH_USUARIOS_BY_ID_SUCCESS = 'FETCH_USUARIOS_BY_ID_SUCCESS';
export const FETCH_USUARIOS_BY_ID_ERROR = 'FETCH_USUARIOS_BY_ID_ERROR';
export const INSERT_USUARIOS_REQUEST = 'INSERT_USUARIOS_REQUEST';
export const INSERT_USUARIOS_SUCCESS = 'INSERT_USUARIOS_SUCCESS';
export const INSERT_USUARIOS_ERROR = 'INSERT_USUARIOS_ERROR';
export const UPDATE_USUARIOS_REQUEST = 'UPDATE_USUARIOS_REQUEST';
export const UPDATE_USUARIOS_SUCCESS = 'UPDATE_USUARIOS_SUCCESS';
export const UPDATE_USUARIOS_ERROR = 'UPDATE_USUARIOS_ERROR';
export const DELETE_USUARIOS_REQUEST = 'DELETE_USUARIOS_REQUEST';
export const DELETE_USUARIOS_SUCCESS = 'DELETE_USUARIOS_SUCCESS';
export const DELETE_USUARIOS_ERROR = 'DELETE_USUARIOS_ERROR';
export const USUARIOS_SET_CURRENT = 'USUARIOS_SET_CURRENT';
export const USUARIOS_SET_META = 'USUARIOS_SET_META'; 
export const USUARIOS_GET_PATH = 'USUARIOS_GET_PATH';
export const USUARIOS_GET_PATH_ERROR = 'USUARIOS_GET_PATH_ERROR';

/**
 * Constantes para acciones de tipoequipo.
 */
export const FETCH_TIPO_EQUIPO_REQUEST = 'FETCH_TIPO_EQUIPO_REQUEST';
export const FETCH_TIPO_EQUIPO_SUCCESS = 'FETCH_TIPO_EQUIPO_SUCCESS';
export const FETCH_TIPO_EQUIPO_ERROR = 'FETCH_TIPO_EQUIPO_ERROR';
export const FETCH_TIPO_EQUIPO_BY_ID_REQUEST = 'FETCH_TIPO_EQUIPO_BY_ID_REQUEST';
export const FETCH_TIPO_EQUIPO_BY_ID_SUCCESS = 'FETCH_TIPO_EQUIPO_BY_ID_SUCCESS';
export const FETCH_TIPO_EQUIPO_BY_ID_ERROR = 'FETCH_TIPO_EQUIPO_BY_ID_ERROR';
export const INSERT_TIPO_EQUIPO_REQUEST = 'INSERT_TIPO_EQUIPO_REQUEST';
export const INSERT_TIPO_EQUIPO_SUCCESS = 'INSERT_TIPO_EQUIPO_SUCCESS';
export const INSERT_TIPO_EQUIPO_ERROR = 'INSERT_TIPO_EQUIPO_ERROR';
export const UPDATE_TIPO_EQUIPO_REQUEST = 'UPDATE_TIPO_EQUIPO_REQUEST';
export const UPDATE_TIPO_EQUIPO_SUCCESS = 'UPDATE_TIPO_EQUIPO_SUCCESS';
export const UPDATE_TIPO_EQUIPO_ERROR = 'UPDATE_TIPO_EQUIPO_ERROR';
export const DELETE_TIPO_EQUIPO_REQUEST = 'DELETE_TIPO_EQUIPO_REQUEST';
export const DELETE_TIPO_EQUIPO_SUCCESS = 'DELETE_TIPO_EQUIPO_SUCCESS';
export const DELETE_TIPO_EQUIPO_ERROR = 'DELETE_TIPO_EQUIPO_ERROR';
export const TIPO_EQUIPO_SET_CURRENT = 'TIPO_EQUIPO_SET_CURRENT';

/**
 * Constantes para acciones de servicios.
 */
export const FETCH_SERVICIOS_REQUEST = 'FETCH_SERVICIOS_REQUEST';
export const FETCH_SERVICIOS_SUCCESS = 'FETCH_SERVICIOS_SUCCESS';
export const FETCH_SERVICIOS_ERROR = 'FETCH_SERVICIOS_ERROR';
export const FETCH_SERVICIOS_BY_ID_REQUEST = 'FETCH_SERVICIOS_BY_ID_REQUEST';
export const FETCH_SERVICIOS_BY_ID_SUCCESS = 'FETCH_SERVICIOS_BY_ID_SUCCESS';
export const FETCH_SERVICIOS_BY_ID_ERROR = 'FETCH_SERVICIOS_BY_ID_ERROR';
export const INSERT_SERVICIOS_REQUEST = 'INSERT_SERVICIOS_REQUEST';
export const INSERT_SERVICIOS_SUCCESS = 'INSERT_SERVICIOS_SUCCESS';
export const INSERT_SERVICIOS_ERROR = 'INSERT_SERVICIOS_ERROR';
export const UPDATE_SERVICIOS_REQUEST = 'UPDATE_SERVICIOS_REQUEST';
export const UPDATE_SERVICIOS_SUCCESS = 'UPDATE_SERVICIOS_SUCCESS';
export const UPDATE_SERVICIOS_ERROR = 'UPDATE_SERVICIOS_ERROR';
export const DELETE_SERVICIOS_REQUEST = 'DELETE_SERVICIOS_REQUEST';
export const DELETE_SERVICIOS_SUCCESS = 'DELETE_SERVICIOS_SUCCESS';
export const DELETE_SERVICIOS_ERROR = 'DELETE_SERVICIOS_ERROR';
export const SERVICIOS_SET_CURRENT = 'SERVICIOS_SET_CURRENT';

/**
 * Constantes para acciones de empresas.
 */
export const FETCH_EMPRESAS_REQUEST = 'FETCH_EMPRESAS_REQUEST';
export const FETCH_EMPRESAS_SUCCESS = 'FETCH_EMPRESAS_SUCCESS';
export const FETCH_EMPRESAS_ERROR = 'FETCH_EMPRESAS_ERROR';
export const FETCH_EMPRESAS_BY_ID_REQUEST = 'FETCH_EMPRESAS_BY_ID_REQUEST';
export const FETCH_EMPRESAS_BY_ID_SUCCESS = 'FETCH_EMPRESAS_BY_ID_SUCCESS';
export const FETCH_EMPRESAS_BY_ID_ERROR = 'FETCH_EMPRESAS_BY_ID_ERROR';
export const INSERT_EMPRESAS_REQUEST = 'INSERT_EMPRESAS_REQUEST';
export const INSERT_EMPRESAS_SUCCESS = 'INSERT_EMPRESAS_SUCCESS';
export const INSERT_EMPRESAS_ERROR = 'INSERT_EMPRESAS_ERROR';
export const UPDATE_EMPRESAS_REQUEST = 'UPDATE_EMPRESAS_REQUEST';
export const UPDATE_EMPRESAS_SUCCESS = 'UPDATE_EMPRESAS_SUCCESS';
export const UPDATE_EMPRESAS_ERROR = 'UPDATE_EMPRESAS_ERROR';
export const DELETE_EMPRESAS_REQUEST = 'DELETE_EMPRESAS_REQUEST';
export const DELETE_EMPRESAS_SUCCESS = 'DELETE_EMPRESAS_SUCCESS';
export const DELETE_EMPRESAS_ERROR = 'DELETE_EMPRESAS_ERROR';
export const EMPRESAS_SET_CURRENT = 'EMPRESAS_SET_CURRENT';

/**
 * Constantes para acciones de clientes.
 */
export const FETCH_CLIENTES_REQUEST = 'FETCH_CLIENTES_REQUEST';
export const FETCH_CLIENTES_SUCCESS = 'FETCH_CLIENTES_SUCCESS';
export const FETCH_CLIENTES_ERROR = 'FETCH_CLIENTES_ERROR';
export const FETCH_CLIENTES_BY_ID_REQUEST = 'FETCH_CLIENTES_BY_ID_REQUEST';
export const FETCH_CLIENTES_BY_ID_SUCCESS = 'FETCH_CLIENTES_BY_ID_SUCCESS';
export const FETCH_CLIENTES_BY_ID_ERROR = 'FETCH_CLIENTES_BY_ID_ERROR';
export const INSERT_CLIENTES_REQUEST = 'INSERT_CLIENTES_REQUEST';
export const INSERT_CLIENTES_SUCCESS = 'INSERT_CLIENTES_SUCCESS';
export const INSERT_CLIENTES_ERROR = 'INSERT_CLIENTES_ERROR';
export const UPDATE_CLIENTES_REQUEST = 'UPDATE_CLIENTES_REQUEST';
export const UPDATE_CLIENTES_SUCCESS = 'UPDATE_CLIENTES_SUCCESS';
export const UPDATE_CLIENTES_ERROR = 'UPDATE_CLIENTES_ERROR';
export const DELETE_CLIENTES_REQUEST = 'DELETE_CLIENTES_REQUEST';
export const DELETE_CLIENTES_SUCCESS = 'DELETE_CLIENTES_SUCCESS';
export const DELETE_CLIENTES_ERROR = 'DELETE_CLIENTES_ERROR';
export const CLIENTES_SET_CURRENT = 'CLIENTES_SET_CURRENT';

/**
 * Constantes para acciones de folios.
 */
export const FETCH_FOLIOS_REQUEST = 'FETCH_FOLIOS_REQUEST';
export const FETCH_FOLIOS_SUCCESS = 'FETCH_FOLIOS_SUCCESS';
export const FETCH_FOLIOS_ERROR = 'FETCH_FOLIOS_ERROR';
export const FETCH_FOLIOS_BY_ID_REQUEST = 'FETCH_FOLIOS_BY_ID_REQUEST';
export const FETCH_FOLIOS_BY_ID_SUCCESS = 'FETCH_FOLIOS_BY_ID_SUCCESS';
export const FETCH_FOLIOS_BY_ID_ERROR = 'FETCH_FOLIOS_BY_ID_ERROR';
export const INSERT_FOLIOS_REQUEST = 'INSERT_FOLIOS_REQUEST';
export const INSERT_FOLIOS_SUCCESS = 'INSERT_FOLIOS_SUCCESS';
export const INSERT_FOLIOS_ERROR = 'INSERT_FOLIOS_ERROR';
export const UPDATE_FOLIOS_REQUEST = 'UPDATE_FOLIOS_REQUEST';
export const UPDATE_FOLIOS_SUCCESS = 'UPDATE_FOLIOS_SUCCESS';
export const UPDATE_FOLIOS_ERROR = 'UPDATE_FOLIOS_ERROR';
export const DELETE_FOLIOS_REQUEST = 'DELETE_FOLIOS_REQUEST';
export const DELETE_FOLIOS_SUCCESS = 'DELETE_FOLIOS_SUCCESS';
export const DELETE_FOLIOS_ERROR = 'DELETE_FOLIOS_ERROR';
export const FOLIOS_SET_CURRENT = 'FOLIOS_SET_CURRENT';

/**
 * Constantes para acciones de estatus.
 */
export const FETCH_ESTATUS_REQUEST = 'FETCH_ESTATUS_REQUEST';
export const FETCH_ESTATUS_SUCCESS = 'FETCH_ESTATUS_SUCCESS';
export const FETCH_ESTATUS_ERROR = 'FETCH_ESTATUS_ERROR';
export const FETCH_ESTATUS_BY_ID_REQUEST = 'FETCH_ESTATUS_BY_ID_REQUEST';
export const FETCH_ESTATUS_BY_ID_SUCCESS = 'FETCH_ESTATUS_BY_ID_SUCCESS';
export const FETCH_ESTATUS_BY_ID_ERROR = 'FETCH_ESTATUS_BY_ID_ERROR';
export const ESTATUS_SET_CURRENT = 'ESTATUS_SET_CURRENT';

/**
 * Constantes para acciones de auth.
 */
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

/**
 * Constantes para acciones de dashboard
 */
export const FETCH_COUNTS_REQUEST = 'FETCH_COUNTS_REQUEST';
export const FETCH_COUNTS_SUCCESS = 'FETCH_COUNTS_SUCCESS';
export const FETCH_COUNTS_ERROR = 'FETCH_COUNTS_ERROR';
export const FETCH_FOLIOS_BY_ESTATUS_REQUEST = 'FETCH_FOLIOS_BY_ESTATUS_REQUEST';
export const FETCH_FOLIOS_BY_ESTATUS_SUCCESS = 'FETCH_FOLIOS_BY_ESTATUS_SUCCESS';
export const FETCH_FOLIOS_BY_ESTATUS_ERROR = 'FETCH_FOLIOS_BY_ESTATUS_ERROR';
export const FETCH_FOLIOS_BY_USUARIO_CREADOR_REQUEST = 'FETCH_FOLIOS_BY_USUARIO_CREADOR_REQUEST';
export const FETCH_FOLIOS_BY_USUARIO_CREADOR_SUCCESS = 'FETCH_FOLIOS_BY_USUARIO_CREADOR_SUCCESS';
export const FETCH_FOLIOS_BY_USUARIO_CREADOR_ERROR = 'FETCH_FOLIOS_BY_USUARIO_CREADOR_ERROR';
export const FETCH_FOLIOS_BY_USUARIO_ASIGNADO_REQUEST = 'FETCH_FOLIOS_BY_USUARIO_ASIGNADO_REQUEST';
export const FETCH_FOLIOS_BY_USUARIO_ASIGNADO_SUCCESS = 'FETCH_FOLIOS_BY_USUARIO_ASIGNADO_SUCCESS';
export const FETCH_FOLIOS_BY_USUARIO_ASIGNADO_ERROR = 'FETCH_FOLIOS_BY_USUARIO_ASIGNADO_ERROR';

/**
 * Constantes para acciones de permisos.
 */
export const FETCH_PERMISOS_REQUEST = 'FETCH_PERMISOS_REQUEST';
export const FETCH_PERMISOS_SUCCESS = 'FETCH_PERMISOS_SUCCESS';
export const FETCH_PERMISOS_ERROR = 'FETCH_PERMISOS_ERROR';